
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author luigy
 */
public class principal extends javax.swing.JFrame {

    DefaultListModel model2 = new DefaultListModel();

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        cargar();
        model2 = new DefaultListModel();

        Cola personatem = new Cola();
        for (int i = 0; i < 10; i++) {
            Aviones.Apilar(personatem);
        }
        HiloAvionAsientos = new HiloAvion(jProgressBar1, jProgressBar2, jProgressBar3, jProgressBar4, jProgressBar5, jProgressBar6, jProgressBar7, jProgressBar8, jProgressBar9, jProgressBar10);
//        ((Aviones)Aviones.getHead().getValor()).setPersonas(emigrantes);
        //   Nodo persona =((Aviones)Aviones.getHead().getValor()).getPersonas().getHead().getNext();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_nuevoRegistro = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        tf_nr_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cb_nr_nacionalidad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_nr_raza = new javax.swing.JComboBox<>();
        cb_nr_deportado = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        bt_NuevoRegistro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cb_nr_origen = new javax.swing.JComboBox<>();
        dc_nr_Fnacimiento = new com.toedter.calendar.JDateChooser();
        jD_lista_de_Personas = new javax.swing.JDialog();
        jB_agregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jL_Personas = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jC_box_Deportados = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jD_ListaDeportados = new javax.swing.JDialog();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jL_Deportados = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jD_NoDeportados = new javax.swing.JDialog();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jL_NoDeportados = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jD_Simulacion = new javax.swing.JDialog();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel13 = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        jLabel14 = new javax.swing.JLabel();
        jProgressBar4 = new javax.swing.JProgressBar();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jProgressBar5 = new javax.swing.JProgressBar();
        jLabel17 = new javax.swing.JLabel();
        jProgressBar6 = new javax.swing.JProgressBar();
        jLabel18 = new javax.swing.JLabel();
        jProgressBar7 = new javax.swing.JProgressBar();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jProgressBar8 = new javax.swing.JProgressBar();
        jLabel21 = new javax.swing.JLabel();
        jProgressBar9 = new javax.swing.JProgressBar();
        jProgressBar10 = new javax.swing.JProgressBar();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jM_I_NuevoRegistro = new javax.swing.JMenuItem();
        jM_I_ListaDePer = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel1.setText("Nombre");

        jLabel2.setText("Nacionalidad");

        cb_nr_nacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afgano", "Aleman", "Arabe", "Argentino", "Autraliano", "Belga", "Boliviano", "Brasileño", "Camboyano", "Canadiense", "Chileno", "Chino", "Colombiano", "Coreano", "Costarricense", "Cubano", "Danes", "Ecuatoriano", "Egipcop", "Salvadoreño", "Escoces", "Español", "Estonio", "Etiope", "Filipino", "Finlandes", "Frances", "Gales", "Griego", "Guatelmalteco", "Haitiano", "Holandes", "Hondureño", "Indones", "Ingles", "Iraqui", "irani", "Irlandes", "Israeli", "Italiano", "Japones", "Jordano", "Laosiano", "Letonia", "Lituania", "Malayo", "Marroqui", "Mexicano", "Nicaraguense", "Noruego", "Panameño", "Paraguayo", "Peruano", "Polaco", "Portugues", "Puertorriqueño", "Dominicano", "Rumano", "Ruso", "Suizo", "Tailandes", "Taiwanes", "Turco", "Ucraniano", "Uruguayo", "Venezolano", "Vietnamita" }));

        jLabel3.setText("Feha de nacimiento");

        jLabel4.setText("Raza");

        cb_nr_raza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Americano", "Europeo", "Africano", "Asiatico", "Caucasico" }));

        cb_nr_deportado.setText("Deportado");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nuevo Registro");

        bt_NuevoRegistro.setText("AGREGAR");
        bt_NuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_NuevoRegistroActionPerformed(evt);
            }
        });

        jLabel6.setText("Pais de origen");

        cb_nr_origen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afganistan", "Aleman", "Arabia Saudita", "Argentina", "Australia", "Belgica", "Bolivia", "Brasil", "Camboya", "Canada", "Chile", "Chile", "China", "Colombia", "Corea", "Costa Rica", "Cuba", "Dinamica", "Ecuador", "Egipto", "El Salvador", "Escocia", "España", "Estonia", "Etiopia", "Filipinas", "Finlandia", "Francia", "Gales", "Grecia", "Guatemala", "Haiti", "Holanda", "Honduras", "Indonesia", "Inglaterra", "Irak", "Iran", "Irlanda", "Israel", "Italia", "Japon", "Jordania", "Laos", "Letonia", "Lituania", "Malasia", "Marruecos", "Mexico", "Nicaragua", "Noruega", "Nueva Zelanda", "Panama", "PAraguay", "Peru", "Polonia", "Portugal", "Puerto Rico", "Republica Dominicana", "Rumania", "Rusia", "Suecia", "Suiza", "Tailandia", "Taiwan", "Turquia", "Ucrania", "Uruguay", "Venezuela", "Vietnam" }));

        javax.swing.GroupLayout jd_nuevoRegistroLayout = new javax.swing.GroupLayout(jd_nuevoRegistro.getContentPane());
        jd_nuevoRegistro.getContentPane().setLayout(jd_nuevoRegistroLayout);
        jd_nuevoRegistroLayout.setHorizontalGroup(
            jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_nuevoRegistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(123, 123, 123))
            .addGroup(jd_nuevoRegistroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_nuevoRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_nr_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_nuevoRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dc_nr_Fnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jd_nuevoRegistroLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_nr_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jd_nuevoRegistroLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cb_nr_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(bt_NuevoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cb_nr_deportado)
                    .addGroup(jd_nuevoRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_nr_raza, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jd_nuevoRegistroLayout.setVerticalGroup(
            jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_nuevoRegistroLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nr_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_nr_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_nr_origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dc_nr_Fnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_nr_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_nr_deportado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_NuevoRegistro)
                .addContainerGap())
        );

        jB_agregar.setText("Agregar");
        jB_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_agregarMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(jL_Personas);

        jButton2.setText("Deportados");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("No Deportados");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel10.setText("Agregar deportados");

        jLabel7.setText("Lista de personas ");

        jButton1.setText("Simulacion");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jD_lista_de_PersonasLayout = new javax.swing.GroupLayout(jD_lista_de_Personas.getContentPane());
        jD_lista_de_Personas.getContentPane().setLayout(jD_lista_de_PersonasLayout);
        jD_lista_de_PersonasLayout.setHorizontalGroup(
            jD_lista_de_PersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_lista_de_PersonasLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jD_lista_de_PersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jD_lista_de_PersonasLayout.createSequentialGroup()
                        .addGroup(jD_lista_de_PersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jD_lista_de_PersonasLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(46, 46, 46))
                            .addGroup(jD_lista_de_PersonasLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)))
                        .addGroup(jD_lista_de_PersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jC_box_Deportados, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jD_lista_de_PersonasLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jB_agregar)))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jD_lista_de_PersonasLayout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jD_lista_de_PersonasLayout.setVerticalGroup(
            jD_lista_de_PersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jD_lista_de_PersonasLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jD_lista_de_PersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jC_box_Deportados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jD_lista_de_PersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_agregar)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(28, 28, 28))
        );

        jButton4.setText("Generar reporte");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(jL_Deportados);

        jLabel9.setText("Deportados");

        javax.swing.GroupLayout jD_ListaDeportadosLayout = new javax.swing.GroupLayout(jD_ListaDeportados.getContentPane());
        jD_ListaDeportados.getContentPane().setLayout(jD_ListaDeportadosLayout);
        jD_ListaDeportadosLayout.setHorizontalGroup(
            jD_ListaDeportadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jD_ListaDeportadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jD_ListaDeportadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addGroup(jD_ListaDeportadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addGap(130, 130, 130))
            .addGroup(jD_ListaDeportadosLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jD_ListaDeportadosLayout.setVerticalGroup(
            jD_ListaDeportadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jD_ListaDeportadosLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(26, 26, 26))
        );

        jButton5.setText("Generar Reporte");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jScrollPane3.setViewportView(jL_NoDeportados);

        jLabel8.setText("No Deportados");

        javax.swing.GroupLayout jD_NoDeportadosLayout = new javax.swing.GroupLayout(jD_NoDeportados.getContentPane());
        jD_NoDeportados.getContentPane().setLayout(jD_NoDeportadosLayout);
        jD_NoDeportadosLayout.setHorizontalGroup(
            jD_NoDeportadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jD_NoDeportadosLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jD_NoDeportadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(94, 94, 94))
            .addGroup(jD_NoDeportadosLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jD_NoDeportadosLayout.setVerticalGroup(
            jD_NoDeportadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jD_NoDeportadosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(25, 25, 25))
        );

        jProgressBar1.setMaximum(5);

        jLabel11.setText("Avion1");

        jLabel12.setText("Avion 2");

        jProgressBar2.setMaximum(5);

        jLabel13.setText("Avion 3");

        jProgressBar3.setMaximum(5);

        jLabel14.setText("Asignando Asientos");

        jProgressBar4.setMaximum(5);

        jLabel15.setText("Avion 4");

        jLabel16.setText("Avion 5");

        jProgressBar5.setMaximum(5);

        jLabel17.setText("Avion 6");

        jProgressBar6.setMaximum(5);

        jLabel18.setText("Avion 7");

        jProgressBar7.setMaximum(5);

        jLabel19.setText("Avion 8");

        jLabel20.setText("Avion9");

        jProgressBar8.setMaximum(5);

        jLabel21.setText("Avion10");

        jProgressBar9.setMaximum(5);

        jProgressBar10.setMaximum(5);

        jButton6.setText("Aceptar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jD_SimulacionLayout = new javax.swing.GroupLayout(jD_Simulacion.getContentPane());
        jD_Simulacion.getContentPane().setLayout(jD_SimulacionLayout);
        jD_SimulacionLayout.setHorizontalGroup(
            jD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_SimulacionLayout.createSequentialGroup()
                .addGroup(jD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jD_SimulacionLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jD_SimulacionLayout.createSequentialGroup()
                                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jProgressBar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jD_SimulacionLayout.createSequentialGroup()
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jProgressBar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jD_SimulacionLayout.createSequentialGroup()
                                .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jProgressBar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jD_SimulacionLayout.createSequentialGroup()
                                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jProgressBar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jD_SimulacionLayout.createSequentialGroup()
                                .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jProgressBar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jD_SimulacionLayout.createSequentialGroup()
                        .addGroup(jD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jD_SimulacionLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel13))
                            .addGroup(jD_SimulacionLayout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(jLabel14))
                            .addGroup(jD_SimulacionLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel15))
                            .addGroup(jD_SimulacionLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addGap(54, 54, 54)))
                .addGap(137, 137, 137))
            .addGroup(jD_SimulacionLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(198, 198, 198))
            .addGroup(jD_SimulacionLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(197, 197, 197))
            .addGroup(jD_SimulacionLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jD_SimulacionLayout.setVerticalGroup(
            jD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_SimulacionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel14)
                .addGap(30, 30, 30)
                .addGroup(jD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20))
                .addGap(12, 12, 12)
                .addGroup(jD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(65, 65, 65))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Inicio");

        jM_I_NuevoRegistro.setText("Nuevo registro");
        jM_I_NuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_I_NuevoRegistroActionPerformed(evt);
            }
        });
        jMenu1.add(jM_I_NuevoRegistro);

        jM_I_ListaDePer.setText("Lista de personas");
        jM_I_ListaDePer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_I_ListaDePerActionPerformed(evt);
            }
        });
        jMenu1.add(jM_I_ListaDePer);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_NuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_NuevoRegistroActionPerformed
        // TODO add your handling code here:

        persona p = new persona(this.tf_nr_nombre.getText(), this.cb_nr_nacionalidad.getSelectedItem().toString(),
                this.dc_nr_Fnacimiento.getDate(), this.cb_nr_raza.getSelectedItem().toString(),
                this.cb_nr_origen.getSelectedItem().toString(), this.cb_nr_deportado.isSelected());

        model2.addElement(p);
        jL_Personas.setModel(model2);
        File archivo = new File("./personas.lu");
        try {
            if (!archivo.exists()) {
                FileOutputStream salida = new FileOutputStream(archivo);
                ObjectOutputStream objeto = new ObjectOutputStream(salida);
                objeto.writeObject(p);
                objeto.flush();
                objeto.close();
                salida.close();
            } else {
                FileInputStream entrada = new FileInputStream(archivo);
                ObjectInputStream objeto = new ObjectInputStream(entrada);
                persona temp;
                Cola lista = new Cola();
                try {

                    while ((temp = (persona) objeto.readObject()) != null) {
                        lista.queue(temp);

                    }
                } catch (EOFException e) {
                }
                objeto.close();
                entrada.close();

                lista.queue(p);
                FileOutputStream salida = new FileOutputStream(archivo);
                ObjectOutputStream objeto2 = new ObjectOutputStream(salida);
                while (!lista.isEmpty()) {
                    objeto2.writeObject((persona) lista.Dequeue());
                }
                objeto2.flush();
                objeto2.close();
                salida.close();
            }
        } catch (Exception e) {
        }
        emigrantes.queue(p);
        this.tf_nr_nombre.setText("");
        this.cb_nr_deportado.setSelected(false);
        this.cb_nr_nacionalidad.setSelectedIndex(0);
        this.cb_nr_origen.setSelectedIndex(0);
        this.cb_nr_raza.setSelectedIndex(0);
        this.dc_nr_Fnacimiento.setDate(null);

    }//GEN-LAST:event_bt_NuevoRegistroActionPerformed

    private void jM_I_NuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_I_NuevoRegistroActionPerformed
        // TODO add your handling code here:
        this.dialog(jd_nuevoRegistro);

    }//GEN-LAST:event_jM_I_NuevoRegistroActionPerformed

    private void jM_I_ListaDePerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_I_ListaDePerActionPerformed
        // TODO add your handling code here:
        jD_lista_de_Personas.pack();
        jD_lista_de_Personas.setModal(true);
        jD_lista_de_Personas.setLocationRelativeTo(this);
        jD_lista_de_Personas.setVisible(true);
    }//GEN-LAST:event_jM_I_ListaDePerActionPerformed

    private void jB_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_agregarMouseClicked
        // TODO add your handling code here:
        int indice = jL_Personas.getSelectedIndex();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        int temp = 0;
        Nodo tem = emigrantes.getHead();
        DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) jC_box_Deportados.getModel();
        while (tem != null) {

            if (temp == indice) {
                if (((persona) tem.getValor()).isDeportado() == false) {
                    ((persona) tem.getValor()).setDeportado(true);
                    modelo1.addElement(tem.getValor());

                    lista_deportados.Apilar(tem.getValor());
                    JOptionPane.showMessageDialog(this, "se deporto exitosamente");

                    persona p = new persona(((persona) tem.getValor()).getNombre(), ((persona) tem.getValor()).getNacionalidad(), ((persona) tem.getValor()).getFNacimiento(), ((persona) tem.getValor()).getRaza(), ((persona) tem.getValor()).getPaisOrigen(), ((persona) tem.getValor()).isDeportado());

                    File archivo = new File("./personasDep.lu");
                    try {
                        if (!archivo.exists()) {
                            FileOutputStream salida = new FileOutputStream(archivo);
                            ObjectOutputStream objeto = new ObjectOutputStream(salida);
                            objeto.writeObject(p);
                            objeto.flush();
                            objeto.close();
                            salida.close();
                        } else {
                            FileInputStream entrada = new FileInputStream(archivo);
                            ObjectInputStream objeto = new ObjectInputStream(entrada);
                            persona temp1;
                            Cola lista = new Cola();
                            try {

                                while ((temp1 = (persona) objeto.readObject()) != null) {
                                    lista.queue(temp1);

                                }
                            } catch (EOFException e) {
                            }
                            objeto.close();
                            entrada.close();

                            lista.queue(p);
                            FileOutputStream salida = new FileOutputStream(archivo);
                            ObjectOutputStream objeto2 = new ObjectOutputStream(salida);
                            while (!lista.isEmpty()) {
                                objeto2.writeObject((persona) lista.Dequeue());
                            }
                            objeto2.flush();
                            objeto2.close();
                            salida.close();
                        }
                    } catch (Exception e) {
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Ya esta deportado la persona escoja a otra");
                }
                System.out.println("------");
                System.out.println(tem.getValor());
            }
            tem = tem.getNext();
            temp++;
        }
        jC_box_Deportados.setModel(modelo1);
        File archivo = new File("./personas.lu");
        archivo.delete();
        tem = emigrantes.getHead();
        File archivo2 = new File("./personas.lu");
        while (tem != null) {

            persona p = new persona(((persona) tem.getValor()).getNombre(), ((persona) tem.getValor()).getNacionalidad(), ((persona) tem.getValor()).getFNacimiento(), ((persona) tem.getValor()).getRaza(), ((persona) tem.getValor()).getPaisOrigen(), ((persona) tem.getValor()).isDeportado());
            
            try {
                if (!archivo2.exists()) {
                    FileOutputStream salida = new FileOutputStream(archivo2);
                    ObjectOutputStream objeto = new ObjectOutputStream(salida);
                    objeto.writeObject(p);
                    objeto.flush();
                    objeto.close();
                    salida.close();
                } else {
                    FileInputStream entrada = new FileInputStream(archivo2);
                    ObjectInputStream objeto = new ObjectInputStream(entrada);
                    persona temp1;
                    Cola lista = new Cola();
                    try {

                        while ((temp1 = (persona) objeto.readObject()) != null) {
                            lista.queue(temp1);

                        }
                    } catch (EOFException e) {
                    }
                    objeto.close();
                    entrada.close();

                    lista.queue(p);
                    FileOutputStream salida = new FileOutputStream(archivo2);
                    ObjectOutputStream objeto2 = new ObjectOutputStream(salida);
                    while (!lista.isEmpty()) {
                        objeto2.writeObject((persona) lista.Dequeue());
                    }
                    objeto2.flush();
                    objeto2.close();
                    salida.close();
                }
            } catch (Exception e) {
            }

            tem = tem.getNext();
        }

        DefaultListModel model = new DefaultListModel();
        model = new DefaultListModel();
        tem = emigrantes.getHead();

        while (tem != null) {

            model.addElement(tem.getValor());

            tem = tem.getNext();

        }
        jL_Personas.setModel(model);

        //**
    }//GEN-LAST:event_jB_agregarMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:

        DefaultListModel model = new DefaultListModel();
        model = new DefaultListModel();
        Nodo tem = emigrantes.getHead();

        while (tem != null) {

            if (((persona) tem.getValor()).isDeportado() == true) {
                model.addElement(tem.getValor());
            }
            tem = tem.getNext();

        }
        jL_Deportados.setModel(model);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        DefaultListModel model = new DefaultListModel();
        model = new DefaultListModel();
        Nodo tem = emigrantes.getHead();

        while (tem != null) {

            if (((persona) tem.getValor()).isDeportado() == false) {
                model.addElement(tem.getValor());
            }
            tem = tem.getNext();

        }
        jL_NoDeportados.setModel(model);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:      
        jD_NoDeportados.pack();
        jD_NoDeportados.setModal(true);
        jD_NoDeportados.setLocationRelativeTo(this);
        jD_NoDeportados.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:

        jD_ListaDeportados.pack();
        jD_ListaDeportados.setModal(true);
        jD_ListaDeportados.setLocationRelativeTo(this);
        jD_ListaDeportados.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jD_Simulacion.pack();
        jD_Simulacion.setModal(true);
        jD_Simulacion.setLocationRelativeTo(this);
        jD_Simulacion.setVisible(true);

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        HiloAvionAsientos.start();
    }//GEN-LAST:event_jButton6MouseClicked
    public void dialog(JDialog a) {
        a.setModal(true);
        a.pack();
        a.setLocationRelativeTo(this);
        a.setVisible(true);
    }

    public void cargar() {
        File archivo = null;
        // DefaultListModel modelo = (DefaultListModel) jL_Personas.getModel();
        try {
            archivo = new File("./personas.lu");
            //Leer lo que ya tiene el archivo y ponerlo en arrayList
            FileInputStream entrada = new FileInputStream(archivo);
            ObjectInputStream objeto = new ObjectInputStream(entrada);

            persona cargando = new persona();
            try {
                while ((cargando = (persona) objeto.readObject()) != null) {
                    System.out.println(cargando);
                    model2.addElement(cargando);
                    jL_Personas.setModel(model2);
                    emigrantes.queue(cargando);

                    // modelo.addElement(cargando);
                    // jL_Personas.setModel(modelo);
                }
            } catch (EOFException e) {
                objeto.close();
                entrada.close();
            }

        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        } catch (IOException ex) {
            System.out.println(ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_NuevoRegistro;
    private javax.swing.JCheckBox cb_nr_deportado;
    private javax.swing.JComboBox<String> cb_nr_nacionalidad;
    private javax.swing.JComboBox<String> cb_nr_origen;
    private javax.swing.JComboBox<String> cb_nr_raza;
    private com.toedter.calendar.JDateChooser dc_nr_Fnacimiento;
    private javax.swing.JButton jB_agregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jC_box_Deportados;
    private javax.swing.JDialog jD_ListaDeportados;
    private javax.swing.JDialog jD_NoDeportados;
    private javax.swing.JDialog jD_Simulacion;
    private javax.swing.JDialog jD_lista_de_Personas;
    private javax.swing.JList<String> jL_Deportados;
    private javax.swing.JList<String> jL_NoDeportados;
    private javax.swing.JList<String> jL_Personas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jM_I_ListaDePer;
    private javax.swing.JMenuItem jM_I_NuevoRegistro;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar10;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    private javax.swing.JProgressBar jProgressBar7;
    private javax.swing.JProgressBar jProgressBar8;
    private javax.swing.JProgressBar jProgressBar9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_nuevoRegistro;
    private javax.swing.JTextField tf_nr_nombre;
    // End of variables declaration//GEN-END:variables
    Cola emigrantes = new Cola();
    Pila lista_deportados = new Pila();
    Pila Aviones = new Pila();
    HiloAvion HiloAvionAsientos;

}
