
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author luigy
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        cargar();
        cargarListaDeportados();
        hiloAbordar = new Habordar(this.pb_AA, emigrantes, deportados, this.lb_emigrantes, this.lb_nomA, angar, enVuelo, this.pb_AV, this.lb_destino);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_nuevoRegistro = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        tf_nr_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cb_nr_nacionalidad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_nr_raza = new javax.swing.JComboBox<>();
        cb_nr_deportado = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        bt_NuevoRegistro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cb_nr_origen = new javax.swing.JComboBox<>();
        dc_nr_Fnacimiento = new com.toedter.calendar.JDateChooser();
        jd_abordar = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        lb_emigrantes = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pb_AV = new javax.swing.JProgressBar();
        lb_nomA = new javax.swing.JLabel();
        pb_AA = new javax.swing.JProgressBar();
        lb_destino = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jD_ListaDe = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jL_Deportados = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel1.setText("Nombre");

        jLabel2.setText("Nacionalidad");

        cb_nr_nacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afgano", "Aleman", "Arabe", "Argentino", "Autraliano", "Belga", "Boliviano", "Brasileño", "Camboyano", "Canadiense", "Chileno", "Chino", "Colombiano", "Coreano", "Costarricense", "Cubano", "Danes", "Ecuatoriano", "Egipcop", "Salvadoreño", "Escoces", "Español", "Estonio", "Etiope", "Filipino", "Finlandes", "Frances", "Gales", "Griego", "Guatelmalteco", "Haitiano", "Holandes", "Hondureño", "Indones", "Ingles", "Iraqui", "irani", "Irlandes", "Israeli", "Italiano", "Japones", "Jordano", "Laosiano", "Letonia", "Lituania", "Malayo", "Marroqui", "Mexicano", "Nicaraguense", "Noruego", "Panameño", "Paraguayo", "Peruano", "Polaco", "Portugues", "Puertorriqueño", "Dominicano", "Rumano", "Ruso", "Suizo", "Tailandes", "Taiwanes", "Turco", "Ucraniano", "Uruguayo", "Venezolano", "Vietnamita" }));

        jLabel3.setText("Feha de nacimiento");

        jLabel4.setText("Raza");

        cb_nr_raza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caucasico", "Hispano", "Afroasiatico", "Idioeuropeo", "Niger-congo" }));

        cb_nr_deportado.setText("Deportado");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nuevo Registro");

        bt_NuevoRegistro.setText("AGREGAR");
        bt_NuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_NuevoRegistroActionPerformed(evt);
            }
        });

        jLabel6.setText("Pais de origen");

        cb_nr_origen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afganistan", "Aleman", "Arabia Saudita", "Argentina", "Australia", "Belgica", "Bolivia", "Brasil", "Camboya", "Canada", "Chile", "Chile", "China", "Colombia", "Corea", "Costa Rica", "Cuba", "Dinamica", "Ecuador", "Egipto", "El Salvador", "Escocia", "España", "Estonia", "Etiopia", "Filipinas", "Finlandia", "Francia", "Gales", "Grecia", "Guatemala", "Haiti", "Holanda", "Honduras", "Indonesia", "Inglaterra", "Irak", "Iran", "Irlanda", "Israel", "Italia", "Japon", "Jordania", "Laos", "Letonia", "Lituania", "Malasia", "Marruecos", "Mexico", "Nicaragua", "Noruega", "Nueva Zelanda", "Panama", "PAraguay", "Peru", "Polonia", "Portugal", "Puerto Rico", "Republica Dominicana", "Rumania", "Rusia", "Suecia", "Suiza", "Tailandia", "Taiwan", "Turquia", "Ucrania", "Uruguay", "Venezuela", "Vietnam" }));

        javax.swing.GroupLayout jd_nuevoRegistroLayout = new javax.swing.GroupLayout(jd_nuevoRegistro.getContentPane());
        jd_nuevoRegistro.getContentPane().setLayout(jd_nuevoRegistroLayout);
        jd_nuevoRegistroLayout.setHorizontalGroup(
            jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_nuevoRegistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(123, 123, 123))
            .addGroup(jd_nuevoRegistroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_nuevoRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_nr_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_nuevoRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dc_nr_Fnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jd_nuevoRegistroLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_nr_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jd_nuevoRegistroLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cb_nr_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(bt_NuevoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cb_nr_deportado)
                    .addGroup(jd_nuevoRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_nr_raza, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jd_nuevoRegistroLayout.setVerticalGroup(
            jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_nuevoRegistroLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nr_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_nr_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_nr_origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dc_nr_Fnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(jd_nuevoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_nr_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_nr_deportado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_NuevoRegistro)
                .addContainerGap())
        );

        jLabel9.setText("Emigrantes en espera");

        jButton1.setText("Iniciar abordaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pb_AV.setMaximum(5);

        pb_AA.setMaximum(5);

        jLabel7.setText("Abordando:");

        jLabel8.setText("Destino:");

        javax.swing.GroupLayout jd_abordarLayout = new javax.swing.GroupLayout(jd_abordar.getContentPane());
        jd_abordar.getContentPane().setLayout(jd_abordarLayout);
        jd_abordarLayout.setHorizontalGroup(
            jd_abordarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_abordarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_abordarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pb_AA, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_abordarLayout.createSequentialGroup()
                        .addGroup(jd_abordarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jd_abordarLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_nomA)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_emigrantes))
                    .addGroup(jd_abordarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pb_AV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                    .addGroup(jd_abordarLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_destino)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jd_abordarLayout.setVerticalGroup(
            jd_abordarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_abordarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jd_abordarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lb_emigrantes))
                .addGap(18, 18, 18)
                .addGroup(jd_abordarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lb_nomA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pb_AA, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_abordarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_destino)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pb_AV, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButton2.setText("Generar Reporte");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(jL_Deportados);

        javax.swing.GroupLayout jD_ListaDeLayout = new javax.swing.GroupLayout(jD_ListaDe.getContentPane());
        jD_ListaDe.getContentPane().setLayout(jD_ListaDeLayout);
        jD_ListaDeLayout.setHorizontalGroup(
            jD_ListaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jD_ListaDeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(54, 54, 54))
            .addGroup(jD_ListaDeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jD_ListaDeLayout.setVerticalGroup(
            jD_ListaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jD_ListaDeLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(28, 28, 28))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Inicio");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Nuevo registro");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Vuelos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Lista");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_NuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_NuevoRegistroActionPerformed
        // TODO add your handling code here:

        persona p = new persona(this.tf_nr_nombre.getText(), this.cb_nr_nacionalidad.getSelectedItem().toString(),
                this.dc_nr_Fnacimiento.getDate(), this.cb_nr_raza.getSelectedItem().toString(),
                this.cb_nr_origen.getSelectedItem().toString(), this.cb_nr_deportado.isSelected());
        File archivo = new File("./personas.lu");
        try {
            if (!archivo.exists()) {
                FileOutputStream salida = new FileOutputStream(archivo);
                ObjectOutputStream objeto = new ObjectOutputStream(salida);
                objeto.writeObject(p);
                objeto.flush();
                objeto.close();
                salida.close();
            } else {
                FileInputStream entrada = new FileInputStream(archivo);
                ObjectInputStream objeto = new ObjectInputStream(entrada);
                persona temp;
                Cola lista = new Cola();
                try {

                    while ((temp = (persona) objeto.readObject()) != null) {
                        lista.queue(temp);

                    }
                } catch (EOFException e) {
                }
                objeto.close();
                entrada.close();

                lista.queue(p);
                FileOutputStream salida = new FileOutputStream(archivo);
                ObjectOutputStream objeto2 = new ObjectOutputStream(salida);
                while (!lista.isEmpty()) {
                    objeto2.writeObject((persona) lista.Dequeue());
                }
                objeto2.flush();
                objeto2.close();
                salida.close();
            }
        } catch (Exception e) {
        }
        emigrantes.queue(p);
        emigrantestemp.queue(p);
        this.tf_nr_nombre.setText("");
        this.cb_nr_deportado.setSelected(false);
        this.cb_nr_nacionalidad.setSelectedIndex(0);
        this.cb_nr_origen.setSelectedIndex(0);
        this.cb_nr_raza.setSelectedIndex(0);
        this.dc_nr_Fnacimiento.setDate(null);

    }//GEN-LAST:event_bt_NuevoRegistroActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dialog(jd_nuevoRegistro);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double cont = 0;
        double control = 1;
        double num = 1;
        Nodo tem = emigrantestemp.getHead();
        while (tem.getNext() != null) {
            if (num == (control / 5)) {
                if (cont == 0) {
                    // cont++;
                }
                cont++;
            }

            control++;
            tem = tem.getNext();
        }
        if (cont >= 1) {
            cont = cont * 5;
        } else {
            cont = 0;
        }
        tem = emigrantes.getHead();
        for (int i = 0; i < cont; i++) {
            ((persona) tem.getValor()).setDeportado(true);
            lista_total.queue(tem.getValor());
            File archivo = new File("./personasDepo.lu");

            persona p = new persona(((persona) tem.getValor()).getNombre(), ((persona) tem.getValor()).getNacionalidad(), ((persona) tem.getValor()).getFNacimiento(), ((persona) tem.getValor()).getRaza(), ((persona) tem.getValor()).getPaisOrigen(), ((persona) tem.getValor()).isDeportado());

            try {
                if (!archivo.exists()) {
                    FileOutputStream salida = new FileOutputStream(archivo);
                    ObjectOutputStream objeto = new ObjectOutputStream(salida);
                    objeto.writeObject(p);
                    objeto.flush();
                    objeto.close();
                    salida.close();
                } else {
                    FileInputStream entrada = new FileInputStream(archivo);
                    ObjectInputStream objeto = new ObjectInputStream(entrada);
                    persona temp;
                    Cola lista = new Cola();
                    try {

                        while ((temp = (persona) objeto.readObject()) != null) {
                            lista.queue(temp);

                        }
                    } catch (EOFException e) {
                    }
                    objeto.close();
                    entrada.close();

                    lista.queue(p);
                    FileOutputStream salida = new FileOutputStream(archivo);
                    ObjectOutputStream objeto2 = new ObjectOutputStream(salida);
                    while (!lista.isEmpty()) {
                        objeto2.writeObject((persona) lista.Dequeue());
                    }
                    objeto2.flush();
                    objeto2.close();
                    salida.close();
                }
            } catch (Exception e) {
            }
            tem = tem.getNext();

            
        }
        tem = emigrantestemp.getHead();
        System.out.println(cont);
        for (double i = 0; i < cont; i++) {

            emigrantestemp.Dequeue();

        }

        tem = emigrantestemp.getHead();

        File archivo2 = new File("./personas.lu");
        archivo2.delete();
        tem = emigrantestemp.getHead();
        while (tem.getNext() != null) {
            File archivo = new File("./personas.lu");

            persona p = new persona(((persona) tem.getValor()).getNombre(), ((persona) tem.getValor()).getNacionalidad(), ((persona) tem.getValor()).getFNacimiento(), ((persona) tem.getValor()).getRaza(), ((persona) tem.getValor()).getPaisOrigen(), ((persona) tem.getValor()).isDeportado());

            try {
                if (!archivo.exists()) {
                    FileOutputStream salida = new FileOutputStream(archivo);
                    ObjectOutputStream objeto = new ObjectOutputStream(salida);
                    objeto.writeObject(p);
                    objeto.flush();
                    objeto.close();
                    salida.close();
                } else {
                    FileInputStream entrada = new FileInputStream(archivo);
                    ObjectInputStream objeto = new ObjectInputStream(entrada);
                    persona temp;
                    Cola lista = new Cola();
                    try {

                        while ((temp = (persona) objeto.readObject()) != null) {
                            lista.queue(temp);

                        }
                    } catch (EOFException e) {
                    }
                    objeto.close();
                    entrada.close();

                    lista.queue(p);
                    FileOutputStream salida = new FileOutputStream(archivo);
                    ObjectOutputStream objeto2 = new ObjectOutputStream(salida);
                    while (!lista.isEmpty()) {
                        objeto2.writeObject((persona) lista.Dequeue());
                    }
                    objeto2.flush();
                    objeto2.close();
                    salida.close();
                }
            } catch (Exception e) {
            }
            tem = tem.getNext();
        }

        System.out.println(control);
        System.out.println(cont);
        hiloAbordar.start();

    }//GEN-LAST:event_jButton1ActionPerformed
    public void escribirDeportados(persona p) {
        File archivo = new File("./deportados.lu");
        try {
            if (!archivo.exists()) {
                FileOutputStream salida = new FileOutputStream(archivo);
                ObjectOutputStream objeto = new ObjectOutputStream(salida);
                objeto.writeObject(p);
                objeto.flush();
                objeto.close();
                salida.close();
            } else {
                FileInputStream entrada = new FileInputStream(archivo);
                ObjectInputStream objeto = new ObjectInputStream(entrada);
                persona temp;
                Cola lista = new Cola();
                try {

                    while ((temp = (persona) objeto.readObject()) != null) {
                        lista.queue(temp);

                    }
                } catch (EOFException e) {
                }
                objeto.close();
                entrada.close();

                lista.queue(p);
                FileOutputStream salida = new FileOutputStream(archivo);
                ObjectOutputStream objeto2 = new ObjectOutputStream(salida);
                while (!lista.isEmpty()) {
                    objeto2.writeObject((persona) lista.Dequeue());
                }
                objeto2.flush();
                objeto2.close();
                salida.close();
            }
        } catch (Exception e) {
        }

    }

    public void escribirEmigrantes(Cola b) {
        File archivo = new File("./personas.lu");
        Cola a = b;
        try {

            FileOutputStream salida = new FileOutputStream(archivo);
            ObjectOutputStream objeto2 = new ObjectOutputStream(salida);
            while (!a.isEmpty()) {
                objeto2.writeObject((persona) a.Dequeue());
            }
            objeto2.flush();
            objeto2.close();
            salida.close();
        } catch (Exception e) {
        }
    }
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i < 10; i++) {
            angar.queue(new Avion("Avion #" + (i + 1), true));
        }
        dialog(this.jd_abordar);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        DefaultListModel model = new DefaultListModel();
        model = new DefaultListModel();
        Nodo tem = lista_total.getHead();

        while (tem != null) {

            if (((persona) tem.getValor()).isDeportado() == true) {
                model.addElement(tem.getValor());
            }
            tem = tem.getNext();

        }
        jL_Deportados.setModel(model);
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
        jD_ListaDe.pack();
        jD_ListaDe.setModal(true);
        jD_ListaDe.setLocationRelativeTo(this);
        jD_ListaDe.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    public void dialog(JDialog a) {
        a.setModal(true);
        a.pack();
        a.setLocationRelativeTo(this);
        a.setVisible(true);
    }

    public void cargar() {
        File archivo = null;
        try {
            archivo = new File("./personas.lu");
            //Leer lo que ya tiene el archivo y ponerlo en arrayList
            FileInputStream entrada = new FileInputStream(archivo);
            ObjectInputStream objeto = new ObjectInputStream(entrada);

            persona cargando = new persona();
            try {
                while ((cargando = (persona) objeto.readObject()) != null) {
                    System.out.println(cargando);
                    emigrantes.queue(cargando);
                    emigrantestemp.queue(cargando);

                }
            } catch (EOFException e) {
                objeto.close();
                entrada.close();
            }

        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        } catch (IOException ex) {
            System.out.println(ex);
        }

    }

    public void cargarListaDeportados() {
        File archivo = null;
        try {
            archivo = new File("./personasDepo.lu");
            //Leer lo que ya tiene el archivo y ponerlo en arrayList
            FileInputStream entrada = new FileInputStream(archivo);
            ObjectInputStream objeto = new ObjectInputStream(entrada);

            persona cargando = new persona();
            try {
                while ((cargando = (persona) objeto.readObject()) != null) {
                   // System.out.println(cargando);
                    lista_total.queue(cargando);
                    //emigrantestemp.queue(cargando);

                }
            } catch (EOFException e) {
                objeto.close();
                entrada.close();
            }

        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        } catch (IOException ex) {
            System.out.println(ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_NuevoRegistro;
    private javax.swing.JCheckBox cb_nr_deportado;
    private javax.swing.JComboBox<String> cb_nr_nacionalidad;
    private javax.swing.JComboBox<String> cb_nr_origen;
    private javax.swing.JComboBox<String> cb_nr_raza;
    private com.toedter.calendar.JDateChooser dc_nr_Fnacimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jD_ListaDe;
    private javax.swing.JList<String> jL_Deportados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_abordar;
    private javax.swing.JDialog jd_nuevoRegistro;
    private javax.swing.JLabel lb_destino;
    private javax.swing.JLabel lb_emigrantes;
    private javax.swing.JLabel lb_nomA;
    private javax.swing.JProgressBar pb_AA;
    private javax.swing.JProgressBar pb_AV;
    private javax.swing.JTextField tf_nr_nombre;
    // End of variables declaration//GEN-END:variables
    Cola emigrantes = new Cola();
    Cola emigrantestemp = new Cola();
    Cola deportados = new Cola();
    Cola lista_total = new Cola();
    Cola angar = new Cola();
    Avion enVuelo;
    Habordar hiloAbordar;

}
